name: ios

on: [push]

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
    - name: Build
      run: xcodebuild
           -scheme NCMB
           -sdk iphonesimulator
           -configuration Debug
           build
